full_name = input("Enter your full name: ")
age = int(input("Enter your age: "))
student_id = input("Enter your student ID: ")
city = input("Enter your city: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
email = input("Enter your email: ")
phone = input("Enter your phone number: ")
favorite_language = input("Enter your favorite programming language: ")
programming_goal = input("Enter your programming goal: ")

print("\n================================================")
print("             AKIBA STUDENT PROFILE")
print("================================================")
print(f"\nName:\t\t\t{full_name}")
print(f"Student ID:\t\t{student_id}")
print(f"Age:\t\t\t{age}")
print(f"City:\t\t\t{city}")
print(f"University:\t\t{university}")
print(f"Department:\t\t{department}")
print(f"Email:\t\t\t{email}")
print(f"Phone:\t\t\t{phone}")
print(f"Favorite Language:\t{favorite_language}")
print("\nProgramming Goal:")
print(programming_goal)
print("================================================")