stud_name = input("Enter your name: ")
stud_id = input("Enter your student ID: ")
dep = input("Enter your department: ")
year = input("Enter your year: ")
uni = input("Enter your university name: ")
phone = input("Enter your phone number: ")

print("+--------------------------------+")
print("|       AKIBA STUDENT CARD       |")
print("+--------------------------------+")
print("| Name: " + stud_name + "        |")
print("| ID: " + stud_id + "            |")
print("| Department: " + dep + "        |")
print("| Year: " + year + "             |")
print("| University: " + uni + "        |")
print("| Phone: " + phone + "           |")
print("+--------------------------------+")

