fullname = input("Enter your fullname: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
uni = input("Enter your university name: ")
dep = input("Enter your department: ")
fav_prog = input("What is your favorite programming language?")
goal = input("What is your programming goal?")

print("===================================")
print("        STUDENT INFORMATION        ")
print("===================================")

print("My name is " + fullname)
print("I am " + age + " years old.")
print("I live in " + city + ".")
print("I study " + dep + " at " + uni + ".")
print("My favorite programming language is " + fav_prog + ".")
print("My programming goal: " + goal + ".")
print("===================================")